[package]
name = "refer-ui"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
leptos = { version = "0.8", features = ["csr"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
console_error_panic_hook = "0.1.7"
leptos_i18n = { version = "0.6", features = ["csr"] }
leptos_meta = "0.8"
log = "0.4.29"
console_log = "1.0.0"
once_cell = "1.20"
web-sys = { version = "0.3", features = [
    "File",
    "FileList",
    "HtmlFormElement",
    "Navigator",
    "Window"
] }
exmex = { version = "0.21.0", features = [] }


[build-dependencies]
leptos_i18n_build = { version = "0.6", features = ["csr", "pretty_print"] }

[package.metadata.leptos-i18n]
default = "en"
locales = ["en", "ru"]

[workspace]
members = ["src-tauri","."]
resolver = "2"

# ← Единственный источник правды для всего проекта!
[workspace.package] 
version = "0.2.0" 
edition = "2024"
authors = ["Yuriy (Jager) Lysov"]
license = "GPL-3.0"

[profile.release]
opt-level = "z" # Maximum optimization by size
lto = true      # Aggressive optimization at the linking stage
panic = "abort" # Remove panic processing (reduces size)
